global:
  # Replace with actual hub value
  hub: hub
  tag: 1.22.6-solo
name: istio-ingressgateway-canary
revision: main
labels: # applies to all labels and selectors
  app: istio-ingressgateway-canary
  istio: istio-ingressgateway-canary
service:
  # Replace with actual load balancer IP and type with LoadBalancer
  # loadBalancerIP: 127.0.0.1
  type: None
autoscaling:
  # Enable autoscaling as needed
  enabled: false
  minReplicas: 5
  maxReplicas: 9
