global:
  # Replace with actual hub value
  hub: hub
  tag: 1.22.6-solo
name: eiap-ingress-gw01-canary
revision: 1-22
labels: # applies to all labels and selectors
  app: eiap-ingress-gw01
  istio: eiap-ingress-gw01
service:
  # Replace with actual load balancer IP and type with LoadBalancer
  # loadBalancerIP: 127.0.0.1
  type: NodePort
autoscaling:
  # Enable autoscaling as needed
  enabled: false
  minReplicas: 5
  maxReplicas: 9
